name: chartlib
description: Framework-agnostic chart library core (similar to src/chartlib/)
version: 0.1.0
publish_to: none

resolution: workspace

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
